In [17]:
from utils import *
from heuristique_glouton import *
from evaluation import *

In [18]:
df_ville,df_object,capacity=parse_ttp_file("a280_n2790_uncorr_10.ttp")

In [19]:
df_ville

       X    Y
1    288  149
2    288  129
3    270  133
4    256  141
5    256  157
..   ...  ...
276  236  145
277  246  141
278  252  125
279  260  129
280  280  133

[280 rows x 2 columns]

In [20]:
df_object

      Profit  Weight  City_Index
1        119       1           2
2        187     896           3
3        997     367           4
4         22     690           5
5        347     613           6
...      ...     ...         ...
2786     351     978         276
2787     181     443         277
2788     800     119         278
2789      28     516         279
2790     449     699         280

[2790 rows x 3 columns]

In [21]:
pi,obj_pris,poids_tot,dict_ville_objet_pris=algo_glouton(df_ville,df_object,capacity)

Loading:  96%|█████████▌| 1214520/1262022 [00:27<00:01, 44263.00weight unit/s, Current Weight=1214520, Nb_ville=279]

In [22]:
for ville in pi:
    print("Dans la ville ",ville," le voleur prend ",len(dict_ville_objet_pris[ville])," objet(s).")

Dans la ville  1  le voleur prend  0  objet(s).
Dans la ville  272  le voleur prend  10  objet(s).
Dans la ville  271  le voleur prend  8  objet(s).
Dans la ville  136  le voleur prend  8  objet(s).
Dans la ville  29  le voleur prend  9  objet(s).
Dans la ville  126  le voleur prend  9  objet(s).
Dans la ville  154  le voleur prend  10  objet(s).
Dans la ville  156  le voleur prend  8  objet(s).
Dans la ville  183  le voleur prend  10  objet(s).
Dans la ville  164  le voleur prend  10  objet(s).
Dans la ville  109  le voleur prend  9  objet(s).
Dans la ville  90  le voleur prend  9  objet(s).
Dans la ville  78  le voleur prend  8  objet(s).
Dans la ville  75  le voleur prend  9  objet(s).
Dans la ville  71  le voleur prend  9  objet(s).
Dans la ville  72  le voleur prend  10  objet(s).
Dans la ville  59  le voleur prend  7  objet(s).
Dans la ville  115  le voleur prend  10  objet(s).
Dans la ville  114  le voleur prend  9  objet(s).
Dans la ville  112  le voleur prend  10  objet(s).
Dans la ville  110  le voleur prend  10  objet(s).
Dans la ville  106  le voleur prend  9  objet(s).
Dans la ville  172  le voleur prend  10  objet(s).
Dans la ville  170  le voleur prend  9  objet(s).
Dans la ville  162  le voleur prend  9  objet(s).
Dans la ville  163  le voleur prend  9  objet(s).
Dans la ville  251  le voleur prend  10  objet(s).
Dans la ville  249  le voleur prend  9  objet(s).
Dans la ville  206  le voleur prend  10  objet(s).
Dans la ville  253  le voleur prend  10  objet(s).
Dans la ville  257  le voleur prend  10  objet(s).
Dans la ville  259  le voleur prend  10  objet(s).
Dans la ville  2  le voleur prend  9  objet(s).
Dans la ville  280  le voleur prend  9  objet(s).
Dans la ville  237  le voleur prend  10  objet(s).
Dans la ville  236  le voleur prend  5  objet(s).
Dans la ville  228  le voleur prend  9  objet(s).
Dans la ville  211  le voleur prend  9  objet(s).
Dans la ville  212  le voleur prend  8  objet(s).
Dans la ville  207  le voleur prend  8  objet(s).
Dans la ville  142  le voleur prend  7  objet(s).
Dans la ville  199  le voleur prend  10  objet(s).
Dans la ville  200  le voleur prend  10  objet(s).
Dans la ville  144  le voleur prend  9  objet(s).
Dans la ville  143  le voleur prend  10  objet(s).
Dans la ville  39  le voleur prend  9  objet(s).
Dans la ville  40  le voleur prend  10  objet(s).
Dans la ville  47  le voleur prend  9  objet(s).
Dans la ville  51  le voleur prend  10  objet(s).
Dans la ville  50  le voleur prend  8  objet(s).
Dans la ville  37  le voleur prend  9  objet(s).
Dans la ville  38  le voleur prend  7  objet(s).
Dans la ville  68  le voleur prend  10  objet(s).
Dans la ville  70  le voleur prend  10  objet(s).
Dans la ville  67  le voleur prend  9  objet(s).
Dans la ville  66  le voleur prend  9  objet(s).
Dans la ville  64  le voleur prend  8  objet(s).
Dans la ville  63  le voleur prend  9  objet(s).
Dans la ville  61  le voleur prend  8  objet(s).
Dans la ville  60  le voleur prend  8  objet(s).
Dans la ville  44  le voleur prend  9  objet(s).
Dans la ville  58  le voleur prend  9  objet(s).
Dans la ville  57  le voleur prend  10  objet(s).
Dans la ville  55  le voleur prend  9  objet(s).
Dans la ville  31  le voleur prend  10  objet(s).
Dans la ville  30  le voleur prend  10  objet(s).
Dans la ville  125  le voleur prend  10  objet(s).
Dans la ville  124  le voleur prend  8  objet(s).
Dans la ville  123  le voleur prend  10  objet(s).
Dans la ville  155  le voleur prend  9  objet(s).
Dans la ville  153  le voleur prend  7  objet(s).
Dans la ville  152  le voleur prend  10  objet(s).
Dans la ville  159  le voleur prend  10  objet(s).
Dans la ville  157  le voleur prend  9  objet(s).
Dans la ville  119  le voleur prend  9  objet(s).
Dans la ville  120  le voleur prend  8  objet(s).
Dans la ville  121  le voleur prend  9  objet(s).
Dans la ville  122  le voleur prend  10  objet(s).
Dans la ville  18  le voleur prend  10  objet(s).
Dans la ville  133  le voleur prend  9  objet(s).
Dans la ville  17  le voleur prend  10  objet(s).
Dans la ville  13  le voleur prend  10  objet(s).
Dans la ville  12  le voleur prend  10  objet(s).
Dans la ville  9  le voleur prend  8  objet(s).
Dans la ville  8  le voleur prend  7  objet(s).
Dans la ville  10  le voleur prend  8  objet(s).
Dans la ville  11  le voleur prend  9  objet(s).
Dans la ville  263  le voleur prend  6  objet(s).
Dans la ville  262  le voleur prend  10  objet(s).
Dans la ville  269  le voleur prend  9  objet(s).
Dans la ville  134  le voleur prend  9  objet(s).
Dans la ville  270  le voleur prend  10  objet(s).
Dans la ville  219  le voleur prend  8  objet(s).
Dans la ville  220  le voleur prend  10  objet(s).
Dans la ville  218  le voleur prend  10  objet(s).
Dans la ville  216  le voleur prend  9  objet(s).
Dans la ville  205  le voleur prend  9  objet(s).
Dans la ville  254  le voleur prend  9  objet(s).
Dans la ville  256  le voleur prend  10  objet(s).
Dans la ville  258  le voleur prend  9  objet(s).
Dans la ville  260  le voleur prend  7  objet(s).
Dans la ville  261  le voleur prend  9  objet(s).
Dans la ville  274  le voleur prend  10  objet(s).
Dans la ville  273  le voleur prend  9  objet(s).
Dans la ville  14  le voleur prend  10  objet(s).
Dans la ville  24  le voleur prend  10  objet(s).
Dans la ville  23  le voleur prend  8  objet(s).
Dans la ville  25  le voleur prend  9  objet(s).
Dans la ville  22  le voleur prend  9  objet(s).
Dans la ville  27  le voleur prend  7  objet(s).
Dans la ville  127  le voleur prend  9  objet(s).
Dans la ville  21  le voleur prend  8  objet(s).
Dans la ville  131  le voleur prend  8  objet(s).
Dans la ville  19  le voleur prend  10  objet(s).
Dans la ville  20  le voleur prend  9  objet(s).
Dans la ville  130  le voleur prend  8  objet(s).
Dans la ville  190  le voleur prend  9  objet(s).
Dans la ville  189  le voleur prend  9  objet(s).
Dans la ville  186  le voleur prend  10  objet(s).
Dans la ville  187  le voleur prend  9  objet(s).
Dans la ville  185  le voleur prend  9  objet(s).
Dans la ville  184  le voleur prend  7  objet(s).
Dans la ville  161  le voleur prend  10  objet(s).
Dans la ville  175  le voleur prend  9  objet(s).
Dans la ville  160  le voleur prend  9  objet(s).
Dans la ville  98  le voleur prend  10  objet(s).
Dans la ville  96  le voleur prend  9  objet(s).
Dans la ville  95  le voleur prend  10  objet(s).
Dans la ville  94  le voleur prend  10  objet(s).
Dans la ville  89  le voleur prend  9  objet(s).
Dans la ville  88  le voleur prend  10  objet(s).
Dans la ville  87  le voleur prend  9  objet(s).
Dans la ville  113  le voleur prend  8  objet(s).
Dans la ville  111  le voleur prend  9  objet(s).
Dans la ville  108  le voleur prend  9  objet(s).
Dans la ville  104  le voleur prend  9  objet(s).
Dans la ville  105  le voleur prend  10  objet(s).
Dans la ville  100  le voleur prend  10  objet(s).
Dans la ville  167  le voleur prend  10  objet(s).
Dans la ville  166  le voleur prend  10  objet(s).
Dans la ville  165  le voleur prend  9  objet(s).
Dans la ville  193  le voleur prend  10  objet(s).
Dans la ville  194  le voleur prend  7  objet(s).
Dans la ville  197  le voleur prend  9  objet(s).
Dans la ville  195  le voleur prend  7  objet(s).
Dans la ville  196  le voleur prend  9  objet(s).
Dans la ville  201  le voleur prend  9  objet(s).
Dans la ville  198  le voleur prend  8  objet(s).
Dans la ville  202  le voleur prend  9  objet(s).
Dans la ville  139  le voleur prend  7  objet(s).
Dans la ville  266  le voleur prend  8  objet(s).
Dans la ville  267  le voleur prend  10  objet(s).
Dans la ville  268  le voleur prend  9  objet(s).
Dans la ville  264  le voleur prend  8  objet(s).
Dans la ville  265  le voleur prend  7  objet(s).
Dans la ville  141  le voleur prend  9  objet(s).
Dans la ville  148  le voleur prend  8  objet(s).
Dans la ville  149  le voleur prend  9  objet(s).
Dans la ville  150  le voleur prend  8  objet(s).
Dans la ville  179  le voleur prend  10  objet(s).
Dans la ville  180  le voleur prend  10  objet(s).
Dans la ville  176  le voleur prend  9  objet(s).
Dans la ville  177  le voleur prend  9  objet(s).
Dans la ville  151  le voleur prend  9  objet(s).
Dans la ville  178  le voleur prend  8  objet(s).
Dans la ville  33  le voleur prend  9  objet(s).
Dans la ville  34  le voleur prend  9  objet(s).
Dans la ville  49  le voleur prend  10  objet(s).
Dans la ville  52  le voleur prend  8  objet(s).
Dans la ville  48  le voleur prend  7  objet(s).
Dans la ville  54  le voleur prend  9  objet(s).
Dans la ville  53  le voleur prend  10  objet(s).
Dans la ville  45  le voleur prend  9  objet(s).
Dans la ville  56  le voleur prend  10  objet(s).
Dans la ville  118  le voleur prend  8  objet(s).
Dans la ville  62  le voleur prend  10  objet(s).
Dans la ville  85  le voleur prend  10  objet(s).
Dans la ville  65  le voleur prend  10  objet(s).
Dans la ville  73  le voleur prend  10  objet(s).
Dans la ville  74  le voleur prend  6  objet(s).
Dans la ville  76  le voleur prend  7  objet(s).
Dans la ville  79  le voleur prend  8  objet(s).
Dans la ville  93  le voleur prend  7  objet(s).
Dans la ville  102  le voleur prend  10  objet(s).
Dans la ville  169  le voleur prend  8  objet(s).
Dans la ville  101  le voleur prend  9  objet(s).
Dans la ville  99  le voleur prend  8  objet(s).
Dans la ville  91  le voleur prend  7  objet(s).
Dans la ville  103  le voleur prend  9  objet(s).
Dans la ville  107  le voleur prend  8  objet(s).
Dans la ville  174  le voleur prend  10  objet(s).
Dans la ville  173  le voleur prend  10  objet(s).
Dans la ville  171  le voleur prend  9  objet(s).
Dans la ville  168  le voleur prend  10  objet(s).
Dans la ville  191  le voleur prend  9  objet(s).
Dans la ville  192  le voleur prend  9  objet(s).
Dans la ville  223  le voleur prend  10  objet(s).
Dans la ville  224  le voleur prend  9  objet(s).
Dans la ville  225  le voleur prend  10  objet(s).
Dans la ville  226  le voleur prend  8  objet(s).
Dans la ville  227  le voleur prend  10  objet(s).
Dans la ville  233  le voleur prend  8  objet(s).
Dans la ville  234  le voleur prend  10  objet(s).
Dans la ville  235  le voleur prend  9  objet(s).
Dans la ville  238  le voleur prend  9  objet(s).
Dans la ville  239  le voleur prend  10  objet(s).
Dans la ville  240  le voleur prend  10  objet(s).
Dans la ville  244  le voleur prend  9  objet(s).
Dans la ville  248  le voleur prend  8  objet(s).
Dans la ville  278  le voleur prend  9  objet(s).
Dans la ville  277  le voleur prend  8  objet(s).
Dans la ville  276  le voleur prend  10  objet(s).
Dans la ville  275  le voleur prend  9  objet(s).
Dans la ville  6  le voleur prend  10  objet(s).
Dans la ville  5  le voleur prend  7  objet(s).
Dans la ville  3  le voleur prend  9  objet(s).
Dans la ville  279  le voleur prend  9  objet(s).
Dans la ville  4  le voleur prend  10  objet(s).
Dans la ville  242  le voleur prend  10  objet(s).
Dans la ville  243  le voleur prend  10  objet(s).
Dans la ville  241  le voleur prend  10  objet(s).
Dans la ville  246  le voleur prend  9  objet(s).
Dans la ville  250  le voleur prend  10  objet(s).
Dans la ville  247  le voleur prend  9  objet(s).
Dans la ville  245  le voleur prend  9  objet(s).
Dans la ville  230  le voleur prend  8  objet(s).
Dans la ville  229  le voleur prend  8  objet(s).
Dans la ville  210  le voleur prend  10  objet(s).
Dans la ville  209  le voleur prend  9  objet(s).
Dans la ville  252  le voleur prend  7  objet(s).
Dans la ville  208  le voleur prend  10  objet(s).
Dans la ville  214  le voleur prend  10  objet(s).
Dans la ville  213  le voleur prend  7  objet(s).
Dans la ville  217  le voleur prend  10  objet(s).
Dans la ville  222  le voleur prend  10  objet(s).
Dans la ville  221  le voleur prend  10  objet(s).
Dans la ville  215  le voleur prend  9  objet(s).
Dans la ville  204  le voleur prend  10  objet(s).
Dans la ville  203  le voleur prend  9  objet(s).
Dans la ville  145  le voleur prend  10  objet(s).
Dans la ville  146  le voleur prend  10  objet(s).
Dans la ville  147  le voleur prend  10  objet(s).
Dans la ville  138  le voleur prend  10  objet(s).
Dans la ville  137  le voleur prend  9  objet(s).
Dans la ville  135  le voleur prend  9  objet(s).
Dans la ville  132  le voleur prend  9  objet(s).
Dans la ville  15  le voleur prend  10  objet(s).
Dans la ville  16  le voleur prend  8  objet(s).
Dans la ville  26  le voleur prend  7  objet(s).
Dans la ville  28  le voleur prend  9  objet(s).
Dans la ville  32  le voleur prend  8  objet(s).
Dans la ville  128  le voleur prend  9  objet(s).
Dans la ville  129  le voleur prend  9  objet(s).
Dans la ville  158  le voleur prend  9  objet(s).
Dans la ville  182  le voleur prend  9  objet(s).
Dans la ville  181  le voleur prend  10  objet(s).
Dans la ville  188  le voleur prend  9  objet(s).
Dans la ville  116  le voleur prend  8  objet(s).
Dans la ville  117  le voleur prend  9  objet(s).
Dans la ville  43  le voleur prend  10  objet(s).
Dans la ville  42  le voleur prend  10  objet(s).
Dans la ville  41  le voleur prend  9  objet(s).
Dans la ville  46  le voleur prend  10  objet(s).
Dans la ville  69  le voleur prend  10  objet(s).
Dans la ville  84  le voleur prend  10  objet(s).
Dans la ville  83  le voleur prend  9  objet(s).
Dans la ville  82  le voleur prend  9  objet(s).
Dans la ville  81  le voleur prend  9  objet(s).
Dans la ville  80  le voleur prend  10  objet(s).
Dans la ville  77  le voleur prend  10  objet(s).
Dans la ville  92  le voleur prend  10  objet(s).
Dans la ville  97  le voleur prend  9  objet(s).
Dans la ville  86  le voleur prend  10  objet(s).
Dans la ville  36  le voleur prend  10  objet(s).
Dans la ville  35  le voleur prend  10  objet(s).
Dans la ville  255  le voleur prend  9  objet(s).
Dans la ville  231  le voleur prend  10  objet(s).
Dans la ville  232  le voleur prend  10  objet(s).
Dans la ville  7  le voleur prend  9  objet(s).
Dans la ville  140  le voleur prend  10  objet(s).

In [23]:
eval_non_lin(pi,df_ville,df_object,dict_ville_objet_pris,obj_pris,capacity)

BENEFICE :  1367196
COUT :  16554.85468322785

1350641.1453167722

In [24]:
eval_lin(pi,df_ville,df_object,dict_ville_objet_pris,obj_pris)

BENEFICE :  1367196
COUT :  3882417382.136667

-3881050186.136667