In [121]:
from utils import *
from heuristique_glouton import *
from evaluation import *

In [122]:
df_ville,df_object,capacity=parse_ttp_file("fnl4461_n22300_uncorr-similar-weights_05.ttp")

In [123]:
df_ville

         X     Y
1     5639  6909
2     5652  6142
3     5654  6101
4     5659  6910
5     5659  6920
...    ...   ...
4457  9140  6830
4458  9143  6779
4459  9158  6901
4460  9166  6932
4461  9176  6953

[4461 rows x 2 columns]

In [124]:
df_object

       Profit  Weight  City_Index
1           1    1008           2
2         896    1006           3
3         367    1006           4
4         690    1001           5
5         613    1006           6
...       ...     ...         ...
22296     696    1000        4457
22297     748    1005        4458
22298     878    1001        4459
22299      94    1009        4460
22300     651    1006        4461

[22300 rows x 3 columns]

In [125]:
pi,obj_pris,poids_tot,dict_ville_objet_pris=algo_glouton(df_ville,df_object,capacity)

Loading: 100%|█████████▉| 10180530/10182055 [1:25:42<00:00, 1979.78weight unit/s, Current Weight=1.02e+7, Nb_ville=4460]

In [126]:
for ville in pi:
    print("Dans la ville ",ville," le voleur prend ",len(dict_ville_objet_pris[ville])," objet(s).")

Dans la ville  1  le voleur prend  0  objet(s).
Dans la ville  2489  le voleur prend  2  objet(s).
Dans la ville  438  le voleur prend  1  objet(s).
Dans la ville  578  le voleur prend  1  objet(s).
Dans la ville  2583  le voleur prend  0  objet(s).
Dans la ville  3511  le voleur prend  1  objet(s).
Dans la ville  3315  le voleur prend  2  objet(s).
Dans la ville  3287  le voleur prend  1  objet(s).
Dans la ville  3374  le voleur prend  3  objet(s).
Dans la ville  3791  le voleur prend  1  objet(s).
Dans la ville  4132  le voleur prend  0  objet(s).
Dans la ville  4032  le voleur prend  0  objet(s).
Dans la ville  4298  le voleur prend  0  objet(s).
Dans la ville  3451  le voleur prend  2  objet(s).
Dans la ville  999  le voleur prend  0  objet(s).
Dans la ville  1018  le voleur prend  0  objet(s).
Dans la ville  1328  le voleur prend  0  objet(s).
Dans la ville  1245  le voleur prend  1  objet(s).
Dans la ville  673  le voleur prend  0  objet(s).
Dans la ville  666  le voleur prend  1  objet(s).
Dans la ville  880  le voleur prend  1  objet(s).
Dans la ville  820  le voleur prend  3  objet(s).
Dans la ville  640  le voleur prend  1  objet(s).
Dans la ville  669  le voleur prend  2  objet(s).
Dans la ville  577  le voleur prend  0  objet(s).
Dans la ville  700  le voleur prend  0  objet(s).
Dans la ville  957  le voleur prend  0  objet(s).
Dans la ville  864  le voleur prend  0  objet(s).
Dans la ville  1041  le voleur prend  1  objet(s).
Dans la ville  2088  le voleur prend  0  objet(s).
Dans la ville  2018  le voleur prend  0  objet(s).
Dans la ville  2118  le voleur prend  0  objet(s).
Dans la ville  1772  le voleur prend  0  objet(s).
Dans la ville  1682  le voleur prend  0  objet(s).
Dans la ville  1147  le voleur prend  0  objet(s).
Dans la ville  1252  le voleur prend  0  objet(s).
Dans la ville  1456  le voleur prend  0  objet(s).
Dans la ville  1410  le voleur prend  1  objet(s).
Dans la ville  496  le voleur prend  0  objet(s).
Dans la ville  709  le voleur prend  0  objet(s).
Dans la ville  559  le voleur prend  1  objet(s).
Dans la ville  503  le voleur prend  2  objet(s).
Dans la ville  453  le voleur prend  0  objet(s).
Dans la ville  484  le voleur prend  2  objet(s).
Dans la ville  1020  le voleur prend  0  objet(s).
Dans la ville  1057  le voleur prend  0  objet(s).
Dans la ville  961  le voleur prend  0  objet(s).
Dans la ville  837  le voleur prend  1  objet(s).
Dans la ville  879  le voleur prend  2  objet(s).
Dans la ville  878  le voleur prend  1  objet(s).
Dans la ville  925  le voleur prend  0  objet(s).
Dans la ville  995  le voleur prend  2  objet(s).
Dans la ville  1075  le voleur prend  2  objet(s).
Dans la ville  2420  le voleur prend  0  objet(s).
Dans la ville  2784  le voleur prend  0  objet(s).
Dans la ville  2702  le voleur prend  1  objet(s).
Dans la ville  2698  le voleur prend  1  objet(s).
Dans la ville  2551  le voleur prend  0  objet(s).
Dans la ville  2548  le voleur prend  2  objet(s).
Dans la ville  2405  le voleur prend  0  objet(s).
Dans la ville  2142  le voleur prend  0  objet(s).
Dans la ville  2173  le voleur prend  0  objet(s).
Dans la ville  2259  le voleur prend  0  objet(s).
Dans la ville  2198  le voleur prend  1  objet(s).
Dans la ville  2524  le voleur prend  1  objet(s).
Dans la ville  2948  le voleur prend  0  objet(s).
Dans la ville  3049  le voleur prend  0  objet(s).
Dans la ville  3001  le voleur prend  0  objet(s).
Dans la ville  3054  le voleur prend  1  objet(s).
Dans la ville  3115  le voleur prend  1  objet(s).
Dans la ville  3253  le voleur prend  3  objet(s).
Dans la ville  3338  le voleur prend  1  objet(s).
Dans la ville  3304  le voleur prend  1  objet(s).
Dans la ville  3221  le voleur prend  1  objet(s).
Dans la ville  3243  le voleur prend  2  objet(s).
Dans la ville  3186  le voleur prend  1  objet(s).
Dans la ville  3282  le voleur prend  1  objet(s).
Dans la ville  3401  le voleur prend  1  objet(s).
Dans la ville  3420  le voleur prend  2  objet(s).
Dans la ville  3376  le voleur prend  1  objet(s).
Dans la ville  3301  le voleur prend  2  objet(s).
Dans la ville  3336  le voleur prend  3  objet(s).
Dans la ville  3375  le voleur prend  3  objet(s).
Dans la ville  3353  le voleur prend  2  objet(s).
Dans la ville  3357  le voleur prend  2  objet(s).
Dans la ville  4109  le voleur prend  0  objet(s).
Dans la ville  4081  le voleur prend  0  objet(s).
Dans la ville  4152  le voleur prend  1  objet(s).
Dans la ville  4139  le voleur prend  1  objet(s).
Dans la ville  3380  le voleur prend  0  objet(s).
Dans la ville  3288  le voleur prend  0  objet(s).
Dans la ville  3327  le voleur prend  0  objet(s).
Dans la ville  3270  le voleur prend  2  objet(s).
Dans la ville  3061  le voleur prend  0  objet(s).
Dans la ville  2806  le voleur prend  0  objet(s).
Dans la ville  2732  le voleur prend  0  objet(s).
Dans la ville  2734  le voleur prend  0  objet(s).
Dans la ville  2478  le voleur prend  0  objet(s).
Dans la ville  2647  le voleur prend  0  objet(s).
Dans la ville  2612  le voleur prend  2  objet(s).
Dans la ville  1768  le voleur prend  0  objet(s).
Dans la ville  1564  le voleur prend  0  objet(s).
Dans la ville  1432  le voleur prend  0  objet(s).
Dans la ville  1497  le voleur prend  2  objet(s).
Dans la ville  1641  le voleur prend  2  objet(s).
Dans la ville  2045  le voleur prend  0  objet(s).
Dans la ville  2153  le voleur prend  0  objet(s).
Dans la ville  2497  le voleur prend  0  objet(s).
Dans la ville  2636  le voleur prend  0  objet(s).
Dans la ville  2724  le voleur prend  0  objet(s).
Dans la ville  2706  le voleur prend  0  objet(s).
Dans la ville  2887  le voleur prend  0  objet(s).
Dans la ville  2829  le voleur prend  0  objet(s).
Dans la ville  2584  le voleur prend  0  objet(s).
Dans la ville  3045  le voleur prend  0  objet(s).
Dans la ville  3450  le voleur prend  0  objet(s).
Dans la ville  3957  le voleur prend  0  objet(s).
Dans la ville  4121  le voleur prend  2  objet(s).
Dans la ville  3693  le voleur prend  0  objet(s).
Dans la ville  3703  le voleur prend  0  objet(s).
Dans la ville  3527  le voleur prend  0  objet(s).
Dans la ville  3549  le voleur prend  0  objet(s).
Dans la ville  3573  le voleur prend  0  objet(s).
Dans la ville  3624  le voleur prend  2  objet(s).
Dans la ville  3276  le voleur prend  0  objet(s).
Dans la ville  3309  le voleur prend  0  objet(s).
Dans la ville  3384  le voleur prend  0  objet(s).
Dans la ville  3458  le voleur prend  0  objet(s).
Dans la ville  3514  le voleur prend  1  objet(s).
Dans la ville  1803  le voleur prend  0  objet(s).
Dans la ville  1688  le voleur prend  0  objet(s).
Dans la ville  1800  le voleur prend  0  objet(s).
Dans la ville  796  le voleur prend  0  objet(s).
Dans la ville  1081  le voleur prend  0  objet(s).
Dans la ville  692  le voleur prend  0  objet(s).
Dans la ville  554  le voleur prend  0  objet(s).
Dans la ville  13  le voleur prend  0  objet(s).
Dans la ville  16  le voleur prend  0  objet(s).
Dans la ville  58  le voleur prend  0  objet(s).
Dans la ville  37  le voleur prend  1  objet(s).
Dans la ville  38  le voleur prend  0  objet(s).
Dans la ville  50  le voleur prend  1  objet(s).
Dans la ville  23  le voleur prend  0  objet(s).
Dans la ville  25  le voleur prend  1  objet(s).
Dans la ville  76  le voleur prend  0  objet(s).
Dans la ville  60  le voleur prend  0  objet(s).
Dans la ville  42  le voleur prend  0  objet(s).
Dans la ville  247  le voleur prend  0  objet(s).
Dans la ville  207  le voleur prend  0  objet(s).
Dans la ville  242  le voleur prend  0  objet(s).
Dans la ville  186  le voleur prend  2  objet(s).
Dans la ville  175  le voleur prend  0  objet(s).
Dans la ville  129  le voleur prend  0  objet(s).
Dans la ville  187  le voleur prend  0  objet(s).
Dans la ville  209  le voleur prend  0  objet(s).
Dans la ville  253  le voleur prend  0  objet(s).
Dans la ville  251  le voleur prend  0  objet(s).
Dans la ville  316  le voleur prend  0  objet(s).
Dans la ville  374  le voleur prend  0  objet(s).
Dans la ville  437  le voleur prend  0  objet(s).
Dans la ville  499  le voleur prend  0  objet(s).
Dans la ville  738  le voleur prend  0  objet(s).
Dans la ville  599  le voleur prend  0  objet(s).
Dans la ville  518  le voleur prend  0  objet(s).
Dans la ville  555  le voleur prend  0  objet(s).
Dans la ville  512  le voleur prend  0  objet(s).
Dans la ville  459  le voleur prend  0  objet(s).
Dans la ville  356  le voleur prend  0  objet(s).
Dans la ville  266  le voleur prend  2  objet(s).
Dans la ville  270  le voleur prend  0  objet(s).
Dans la ville  238  le voleur prend  1  objet(s).
Dans la ville  239  le voleur prend  0  objet(s).
Dans la ville  231  le voleur prend  0  objet(s).
Dans la ville  206  le voleur prend  0  objet(s).
Dans la ville  215  le voleur prend  1  objet(s).
Dans la ville  197  le voleur prend  2  objet(s).
Dans la ville  178  le voleur prend  0  objet(s).
Dans la ville  195  le voleur prend  0  objet(s).
Dans la ville  185  le voleur prend  1  objet(s).
Dans la ville  184  le voleur prend  1  objet(s).
Dans la ville  201  le voleur prend  0  objet(s).
Dans la ville  208  le voleur prend  2  objet(s).
Dans la ville  212  le voleur prend  0  objet(s).
Dans la ville  200  le voleur prend  0  objet(s).
Dans la ville  199  le voleur prend  1  objet(s).
Dans la ville  198  le voleur prend  1  objet(s).
Dans la ville  181  le voleur prend  1  objet(s).
Dans la ville  102  le voleur prend  0  objet(s).
Dans la ville  115  le voleur prend  0  objet(s).
Dans la ville  114  le voleur prend  1  objet(s).
Dans la ville  48  le voleur prend  0  objet(s).
Dans la ville  17  le voleur prend  0  objet(s).
Dans la ville  19  le voleur prend  0  objet(s).
Dans la ville  64  le voleur prend  0  objet(s).
Dans la ville  30  le voleur prend  1  objet(s).
Dans la ville  55  le voleur prend  0  objet(s).
Dans la ville  49  le voleur prend  0  objet(s).
Dans la ville  28  le voleur prend  3  objet(s).
Dans la ville  27  le voleur prend  1  objet(s).
Dans la ville  3  le voleur prend  1  objet(s).
Dans la ville  11  le voleur prend  1  objet(s).
Dans la ville  2  le voleur prend  0  objet(s).
Dans la ville  6  le voleur prend  0  objet(s).
Dans la ville  8  le voleur prend  1  objet(s).
Dans la ville  15  le voleur prend  0  objet(s).
Dans la ville  29  le voleur prend  2  objet(s).
Dans la ville  20  le voleur prend  2  objet(s).
Dans la ville  26  le voleur prend  0  objet(s).
Dans la ville  40  le voleur prend  1  objet(s).
Dans la ville  46  le voleur prend  0  objet(s).
Dans la ville  67  le voleur prend  1  objet(s).
Dans la ville  62  le voleur prend  2  objet(s).
Dans la ville  44  le voleur prend  1  objet(s).
Dans la ville  33  le voleur prend  1  objet(s).
Dans la ville  9  le voleur prend  0  objet(s).
Dans la ville  18  le voleur prend  0  objet(s).
Dans la ville  22  le voleur prend  0  objet(s).
Dans la ville  32  le voleur prend  1  objet(s).
Dans la ville  21  le voleur prend  0  objet(s).
Dans la ville  24  le voleur prend  0  objet(s).
Dans la ville  36  le voleur prend  1  objet(s).
Dans la ville  130  le voleur prend  0  objet(s).
Dans la ville  144  le voleur prend  0  objet(s).
Dans la ville  116  le voleur prend  1  objet(s).
Dans la ville  127  le voleur prend  1  objet(s).
Dans la ville  149  le voleur prend  0  objet(s).
Dans la ville  152  le voleur prend  2  objet(s).
Dans la ville  154  le voleur prend  0  objet(s).
Dans la ville  161  le voleur prend  0  objet(s).
Dans la ville  160  le voleur prend  1  objet(s).
Dans la ville  141  le voleur prend  1  objet(s).
Dans la ville  119  le voleur prend  2  objet(s).
Dans la ville  106  le voleur prend  0  objet(s).
Dans la ville  89  le voleur prend  1  objet(s).
Dans la ville  71  le voleur prend  2  objet(s).
Dans la ville  57  le voleur prend  0  objet(s).
Dans la ville  59  le voleur prend  2  objet(s).
Dans la ville  69  le voleur prend  1  objet(s).
Dans la ville  93  le voleur prend  2  objet(s).
Dans la ville  84  le voleur prend  1  objet(s).
Dans la ville  63  le voleur prend  2  objet(s).
Dans la ville  73  le voleur prend  1  objet(s).
Dans la ville  75  le voleur prend  0  objet(s).
Dans la ville  83  le voleur prend  1  objet(s).
Dans la ville  112  le voleur prend  1  objet(s).
Dans la ville  210  le voleur prend  0  objet(s).
Dans la ville  196  le voleur prend  0  objet(s).
Dans la ville  192  le voleur prend  0  objet(s).
Dans la ville  194  le voleur prend  0  objet(s).
Dans la ville  188  le voleur prend  1  objet(s).
Dans la ville  216  le voleur prend  2  objet(s).
Dans la ville  204  le voleur prend  0  objet(s).
Dans la ville  217  le voleur prend  2  objet(s).
Dans la ville  218  le voleur prend  0  objet(s).
Dans la ville  213  le voleur prend  2  objet(s).
Dans la ville  225  le voleur prend  0  objet(s).
Dans la ville  236  le voleur prend  1  objet(s).
Dans la ville  248  le voleur prend  1  objet(s).
Dans la ville  228  le voleur prend  0  objet(s).
Dans la ville  214  le voleur prend  1  objet(s).
Dans la ville  240  le voleur prend  1  objet(s).
Dans la ville  254  le voleur prend  1  objet(s).
Dans la ville  308  le voleur prend  1  objet(s).
Dans la ville  281  le voleur prend  1  objet(s).
Dans la ville  279  le voleur prend  1  objet(s).
Dans la ville  295  le voleur prend  1  objet(s).
Dans la ville  342  le voleur prend  1  objet(s).
Dans la ville  367  le voleur prend  0  objet(s).
Dans la ville  420  le voleur prend  0  objet(s).
Dans la ville  421  le voleur prend  1  objet(s).
Dans la ville  404  le voleur prend  0  objet(s).
Dans la ville  435  le voleur prend  0  objet(s).
Dans la ville  449  le voleur prend  1  objet(s).
Dans la ville  476  le voleur prend  0  objet(s).
Dans la ville  479  le voleur prend  0  objet(s).
Dans la ville  433  le voleur prend  2  objet(s).
Dans la ville  419  le voleur prend  2  objet(s).
Dans la ville  447  le voleur prend  2  objet(s).
Dans la ville  422  le voleur prend  1  objet(s).
Dans la ville  370  le voleur prend  1  objet(s).
Dans la ville  301  le voleur prend  0  objet(s).
Dans la ville  322  le voleur prend  1  objet(s).
Dans la ville  297  le voleur prend  0  objet(s).
Dans la ville  262  le voleur prend  1  objet(s).
Dans la ville  275  le voleur prend  0  objet(s).
Dans la ville  255  le voleur prend  2  objet(s).
Dans la ville  321  le voleur prend  0  objet(s).
Dans la ville  288  le voleur prend  1  objet(s).
Dans la ville  305  le voleur prend  1  objet(s).
Dans la ville  350  le voleur prend  1  objet(s).
Dans la ville  373  le voleur prend  0  objet(s).
Dans la ville  410  le voleur prend  1  objet(s).
Dans la ville  454  le voleur prend  0  objet(s).
Dans la ville  472  le voleur prend  1  objet(s).
Dans la ville  658  le voleur prend  0  objet(s).
Dans la ville  832  le voleur prend  0  objet(s).
Dans la ville  831  le voleur prend  2  objet(s).
Dans la ville  862  le voleur prend  0  objet(s).
Dans la ville  919  le voleur prend  2  objet(s).
Dans la ville  922  le voleur prend  0  objet(s).
Dans la ville  1026  le voleur prend  0  objet(s).
Dans la ville  976  le voleur prend  1  objet(s).
Dans la ville  870  le voleur prend  1  objet(s).
Dans la ville  1842  le voleur prend  0  objet(s).
Dans la ville  1665  le voleur prend  0  objet(s).
Dans la ville  1753  le voleur prend  0  objet(s).
Dans la ville  1536  le voleur prend  0  objet(s).
Dans la ville  1635  le voleur prend  0  objet(s).
Dans la ville  1632  le voleur prend  1  objet(s).
Dans la ville  1268  le voleur prend  0  objet(s).
Dans la ville  1469  le voleur prend  0  objet(s).
Dans la ville  1301  le voleur prend  0  objet(s).
Dans la ville  1327  le voleur prend  0  objet(s).
Dans la ville  1278  le voleur prend  1  objet(s).
Dans la ville  1175  le voleur prend  0  objet(s).
Dans la ville  973  le voleur prend  0  objet(s).
Dans la ville  986  le voleur prend  0  objet(s).
Dans la ville  1201  le voleur prend  0  objet(s).
Dans la ville  1218  le voleur prend  1  objet(s).
Dans la ville  1173  le voleur prend  1  objet(s).
Dans la ville  1429  le voleur prend  0  objet(s).
Dans la ville  1398  le voleur prend  2  objet(s).
Dans la ville  1226  le voleur prend  0  objet(s).
Dans la ville  1191  le voleur prend  0  objet(s).
Dans la ville  1094  le voleur prend  1  objet(s).
Dans la ville  1198  le voleur prend  0  objet(s).
Dans la ville  1219  le voleur prend  0  objet(s).
Dans la ville  1286  le voleur prend  0  objet(s).
Dans la ville  1236  le voleur prend  0  objet(s).
Dans la ville  1208  le voleur prend  0  objet(s).
Dans la ville  1186  le voleur prend  0  objet(s).
Dans la ville  1132  le voleur prend  1  objet(s).
Dans la ville  1058  le voleur prend  1  objet(s).
Dans la ville  1017  le voleur prend  2  objet(s).
Dans la ville  850  le voleur prend  0  objet(s).
Dans la ville  800  le voleur prend  0  objet(s).
Dans la ville  843  le voleur prend  0  objet(s).
Dans la ville  805  le voleur prend  0  objet(s).
Dans la ville  801  le voleur prend  0  objet(s).
Dans la ville  731  le voleur prend  0  objet(s).
Dans la ville  764  le voleur prend  0  objet(s).
Dans la ville  833  le voleur prend  0  objet(s).
Dans la ville  814  le voleur prend  0  objet(s).
Dans la ville  744  le voleur prend  1  objet(s).
Dans la ville  683  le voleur prend  0  objet(s).
Dans la ville  724  le voleur prend  1  objet(s).
Dans la ville  788  le voleur prend  0  objet(s).
Dans la ville  825  le voleur prend  0  objet(s).
Dans la ville  1045  le voleur prend  0  objet(s).
Dans la ville  948  le voleur prend  2  objet(s).
Dans la ville  954  le voleur prend  0  objet(s).
Dans la ville  852  le voleur prend  0  objet(s).
Dans la ville  808  le voleur prend  0  objet(s).
Dans la ville  886  le voleur prend  1  objet(s).
Dans la ville  641  le voleur prend  0  objet(s).
Dans la ville  544  le voleur prend  0  objet(s).
Dans la ville  467  le voleur prend  0  objet(s).
Dans la ville  423  le voleur prend  0  objet(s).
Dans la ville  426  le voleur prend  2  objet(s).
Dans la ville  361  le voleur prend  0  objet(s).
Dans la ville  397  le voleur prend  2  objet(s).
Dans la ville  488  le voleur prend  0  objet(s).
Dans la ville  475  le voleur prend  1  objet(s).
Dans la ville  402  le voleur prend  0  objet(s).
Dans la ville  332  le voleur prend  0  objet(s).
Dans la ville  353  le voleur prend  0  objet(s).
Dans la ville  328  le voleur prend  0  objet(s).
Dans la ville  307  le voleur prend  1  objet(s).
Dans la ville  264  le voleur prend  0  objet(s).
Dans la ville  267  le voleur prend  0  objet(s).
Dans la ville  299  le voleur prend  1  objet(s).
Dans la ville  291  le voleur prend  1  objet(s).
Dans la ville  226  le voleur prend  2  objet(s).
Dans la ville  220  le voleur prend  0  objet(s).
Dans la ville  224  le voleur prend  1  objet(s).
Dans la ville  257  le voleur prend  2  objet(s).
Dans la ville  258  le voleur prend  0  objet(s).
Dans la ville  260  le voleur prend  0  objet(s).
Dans la ville  296  le voleur prend  0  objet(s).
Dans la ville  263  le voleur prend  0  objet(s).
Dans la ville  265  le voleur prend  2  objet(s).
Dans la ville  285  le voleur prend  1  objet(s).
Dans la ville  319  le voleur prend  0  objet(s).
Dans la ville  311  le voleur prend  2  objet(s).
Dans la ville  337  le voleur prend  0  objet(s).
Dans la ville  338  le voleur prend  2  objet(s).
Dans la ville  396  le voleur prend  2  objet(s).
Dans la ville  412  le voleur prend  1  objet(s).
Dans la ville  491  le voleur prend  0  objet(s).
Dans la ville  480  le voleur prend  1  objet(s).
Dans la ville  489  le voleur prend  1  objet(s).
Dans la ville  416  le voleur prend  2  objet(s).
Dans la ville  413  le voleur prend  1  objet(s).
Dans la ville  456  le voleur prend  1  objet(s).
Dans la ville  525  le voleur prend  1  objet(s).
Dans la ville  508  le voleur prend  1  objet(s).
Dans la ville  527  le voleur prend  1  objet(s).
Dans la ville  636  le voleur prend  1  objet(s).

In [127]:
eval_non_lin(pi,df_ville,df_object,dict_ville_objet_pris,obj_pris,capacity)

BENEFICE :  7096853
COUT :  441480.57384640677

6655372.426153593

In [128]:
eval_lin(pi,df_ville,df_object,dict_ville_objet_pris,obj_pris)

BENEFICE :  7096853
COUT :  685112044773.9786

-685104947920.9786