In [1]:
from utils import *
from heuristique_glouton import *
from heuristique_itérative import *
from evaluation import *
from Lin_prog import *

In [2]:
df_ville,df_object,capacity=parse_ttp_file("a280_n2790_uncorr_10.ttp")

In [3]:
df_ville

       X    Y
1    288  149
2    288  129
3    270  133
4    256  141
5    256  157
..   ...  ...
276  236  145
277  246  141
278  252  125
279  260  129
280  280  133

[280 rows x 2 columns]

In [4]:
df_object

      Profit  Weight  City_Index
1        119       1           2
2        187     896           3
3        997     367           4
4         22     690           5
5        347     613           6
...      ...     ...         ...
2786     351     978         276
2787     181     443         277
2788     800     119         278
2789      28     516         279
2790     449     699         280

[2790 rows x 3 columns]

In [5]:
pi,obj_pris,poids_tot,dict_ville_objet_pris=algo_glouton(df_ville,df_object,capacity)

Loading:  96%|█████████▌| 1214520/1262022 [00:45<00:01, 26707.03weight unit/s, Current Weight=1214520, Nb_ville=279]

In [6]:
for ville in pi:
    print("Dans la ville ",ville," le voleur prend ",len(dict_ville_objet_pris[ville])," objet(s).")

Dans la ville  1  le voleur prend  0  objet(s).
Dans la ville  140  le voleur prend  10  objet(s).
Dans la ville  7  le voleur prend  9  objet(s).
Dans la ville  232  le voleur prend  10  objet(s).
Dans la ville  231  le voleur prend  10  objet(s).
Dans la ville  255  le voleur prend  9  objet(s).
Dans la ville  35  le voleur prend  10  objet(s).
Dans la ville  36  le voleur prend  10  objet(s).
Dans la ville  86  le voleur prend  10  objet(s).
Dans la ville  97  le voleur prend  9  objet(s).
Dans la ville  92  le voleur prend  10  objet(s).
Dans la ville  77  le voleur prend  10  objet(s).
Dans la ville  80  le voleur prend  10  objet(s).
Dans la ville  81  le voleur prend  9  objet(s).
Dans la ville  82  le voleur prend  9  objet(s).
Dans la ville  83  le voleur prend  9  objet(s).
Dans la ville  84  le voleur prend  10  objet(s).
Dans la ville  69  le voleur prend  10  objet(s).
Dans la ville  46  le voleur prend  10  objet(s).
Dans la ville  41  le voleur prend  9  objet(s).
Dans la ville  42  le voleur prend  10  objet(s).
Dans la ville  43  le voleur prend  10  objet(s).
Dans la ville  117  le voleur prend  9  objet(s).
Dans la ville  116  le voleur prend  8  objet(s).
Dans la ville  188  le voleur prend  9  objet(s).
Dans la ville  181  le voleur prend  10  objet(s).
Dans la ville  182  le voleur prend  9  objet(s).
Dans la ville  158  le voleur prend  9  objet(s).
Dans la ville  129  le voleur prend  9  objet(s).
Dans la ville  128  le voleur prend  9  objet(s).
Dans la ville  32  le voleur prend  8  objet(s).
Dans la ville  28  le voleur prend  9  objet(s).
Dans la ville  26  le voleur prend  7  objet(s).
Dans la ville  16  le voleur prend  8  objet(s).
Dans la ville  15  le voleur prend  10  objet(s).
Dans la ville  132  le voleur prend  9  objet(s).
Dans la ville  135  le voleur prend  9  objet(s).
Dans la ville  137  le voleur prend  9  objet(s).
Dans la ville  138  le voleur prend  10  objet(s).
Dans la ville  147  le voleur prend  10  objet(s).
Dans la ville  146  le voleur prend  10  objet(s).
Dans la ville  145  le voleur prend  10  objet(s).
Dans la ville  203  le voleur prend  9  objet(s).
Dans la ville  204  le voleur prend  10  objet(s).
Dans la ville  215  le voleur prend  9  objet(s).
Dans la ville  221  le voleur prend  10  objet(s).
Dans la ville  222  le voleur prend  10  objet(s).
Dans la ville  217  le voleur prend  10  objet(s).
Dans la ville  213  le voleur prend  7  objet(s).
Dans la ville  214  le voleur prend  10  objet(s).
Dans la ville  208  le voleur prend  10  objet(s).
Dans la ville  252  le voleur prend  7  objet(s).
Dans la ville  209  le voleur prend  9  objet(s).
Dans la ville  210  le voleur prend  10  objet(s).
Dans la ville  229  le voleur prend  8  objet(s).
Dans la ville  230  le voleur prend  8  objet(s).
Dans la ville  245  le voleur prend  9  objet(s).
Dans la ville  247  le voleur prend  9  objet(s).
Dans la ville  250  le voleur prend  10  objet(s).
Dans la ville  246  le voleur prend  9  objet(s).
Dans la ville  241  le voleur prend  10  objet(s).
Dans la ville  243  le voleur prend  10  objet(s).
Dans la ville  242  le voleur prend  10  objet(s).
Dans la ville  4  le voleur prend  10  objet(s).
Dans la ville  279  le voleur prend  9  objet(s).
Dans la ville  3  le voleur prend  9  objet(s).
Dans la ville  5  le voleur prend  7  objet(s).
Dans la ville  6  le voleur prend  10  objet(s).
Dans la ville  275  le voleur prend  9  objet(s).
Dans la ville  276  le voleur prend  10  objet(s).
Dans la ville  277  le voleur prend  8  objet(s).
Dans la ville  278  le voleur prend  9  objet(s).
Dans la ville  248  le voleur prend  8  objet(s).
Dans la ville  244  le voleur prend  9  objet(s).
Dans la ville  240  le voleur prend  10  objet(s).
Dans la ville  239  le voleur prend  10  objet(s).
Dans la ville  238  le voleur prend  9  objet(s).
Dans la ville  235  le voleur prend  9  objet(s).
Dans la ville  234  le voleur prend  10  objet(s).
Dans la ville  233  le voleur prend  8  objet(s).
Dans la ville  227  le voleur prend  10  objet(s).
Dans la ville  226  le voleur prend  8  objet(s).
Dans la ville  225  le voleur prend  10  objet(s).
Dans la ville  224  le voleur prend  9  objet(s).
Dans la ville  223  le voleur prend  10  objet(s).
Dans la ville  192  le voleur prend  9  objet(s).
Dans la ville  191  le voleur prend  9  objet(s).
Dans la ville  168  le voleur prend  10  objet(s).
Dans la ville  171  le voleur prend  9  objet(s).
Dans la ville  173  le voleur prend  10  objet(s).
Dans la ville  174  le voleur prend  10  objet(s).
Dans la ville  107  le voleur prend  8  objet(s).
Dans la ville  103  le voleur prend  9  objet(s).
Dans la ville  91  le voleur prend  7  objet(s).
Dans la ville  99  le voleur prend  8  objet(s).
Dans la ville  101  le voleur prend  9  objet(s).
Dans la ville  169  le voleur prend  8  objet(s).
Dans la ville  102  le voleur prend  10  objet(s).
Dans la ville  93  le voleur prend  7  objet(s).
Dans la ville  79  le voleur prend  8  objet(s).
Dans la ville  76  le voleur prend  7  objet(s).
Dans la ville  74  le voleur prend  6  objet(s).
Dans la ville  73  le voleur prend  10  objet(s).
Dans la ville  65  le voleur prend  10  objet(s).
Dans la ville  85  le voleur prend  10  objet(s).
Dans la ville  62  le voleur prend  10  objet(s).
Dans la ville  118  le voleur prend  8  objet(s).
Dans la ville  56  le voleur prend  10  objet(s).
Dans la ville  45  le voleur prend  9  objet(s).
Dans la ville  53  le voleur prend  10  objet(s).
Dans la ville  54  le voleur prend  9  objet(s).
Dans la ville  48  le voleur prend  7  objet(s).
Dans la ville  52  le voleur prend  8  objet(s).
Dans la ville  49  le voleur prend  10  objet(s).
Dans la ville  34  le voleur prend  9  objet(s).
Dans la ville  33  le voleur prend  9  objet(s).
Dans la ville  178  le voleur prend  8  objet(s).
Dans la ville  151  le voleur prend  9  objet(s).
Dans la ville  177  le voleur prend  9  objet(s).
Dans la ville  176  le voleur prend  9  objet(s).
Dans la ville  180  le voleur prend  10  objet(s).
Dans la ville  179  le voleur prend  10  objet(s).
Dans la ville  150  le voleur prend  8  objet(s).
Dans la ville  149  le voleur prend  9  objet(s).
Dans la ville  148  le voleur prend  8  objet(s).
Dans la ville  141  le voleur prend  9  objet(s).
Dans la ville  265  le voleur prend  7  objet(s).
Dans la ville  264  le voleur prend  8  objet(s).
Dans la ville  268  le voleur prend  9  objet(s).
Dans la ville  267  le voleur prend  10  objet(s).
Dans la ville  266  le voleur prend  8  objet(s).
Dans la ville  139  le voleur prend  7  objet(s).
Dans la ville  202  le voleur prend  9  objet(s).
Dans la ville  198  le voleur prend  8  objet(s).
Dans la ville  201  le voleur prend  9  objet(s).
Dans la ville  196  le voleur prend  9  objet(s).
Dans la ville  195  le voleur prend  7  objet(s).
Dans la ville  197  le voleur prend  9  objet(s).
Dans la ville  194  le voleur prend  7  objet(s).
Dans la ville  193  le voleur prend  10  objet(s).
Dans la ville  165  le voleur prend  9  objet(s).
Dans la ville  166  le voleur prend  10  objet(s).
Dans la ville  167  le voleur prend  10  objet(s).
Dans la ville  100  le voleur prend  10  objet(s).
Dans la ville  105  le voleur prend  10  objet(s).
Dans la ville  104  le voleur prend  9  objet(s).
Dans la ville  108  le voleur prend  9  objet(s).
Dans la ville  111  le voleur prend  9  objet(s).
Dans la ville  113  le voleur prend  8  objet(s).
Dans la ville  87  le voleur prend  9  objet(s).
Dans la ville  88  le voleur prend  10  objet(s).
Dans la ville  89  le voleur prend  9  objet(s).
Dans la ville  94  le voleur prend  10  objet(s).
Dans la ville  95  le voleur prend  10  objet(s).
Dans la ville  96  le voleur prend  9  objet(s).
Dans la ville  98  le voleur prend  10  objet(s).
Dans la ville  160  le voleur prend  9  objet(s).
Dans la ville  175  le voleur prend  9  objet(s).
Dans la ville  161  le voleur prend  10  objet(s).
Dans la ville  184  le voleur prend  7  objet(s).
Dans la ville  185  le voleur prend  9  objet(s).
Dans la ville  187  le voleur prend  9  objet(s).
Dans la ville  186  le voleur prend  10  objet(s).
Dans la ville  189  le voleur prend  9  objet(s).
Dans la ville  190  le voleur prend  9  objet(s).
Dans la ville  130  le voleur prend  8  objet(s).
Dans la ville  20  le voleur prend  9  objet(s).
Dans la ville  19  le voleur prend  10  objet(s).
Dans la ville  131  le voleur prend  8  objet(s).
Dans la ville  21  le voleur prend  8  objet(s).
Dans la ville  127  le voleur prend  9  objet(s).
Dans la ville  27  le voleur prend  7  objet(s).
Dans la ville  22  le voleur prend  9  objet(s).
Dans la ville  25  le voleur prend  9  objet(s).
Dans la ville  23  le voleur prend  8  objet(s).
Dans la ville  24  le voleur prend  10  objet(s).
Dans la ville  14  le voleur prend  10  objet(s).
Dans la ville  273  le voleur prend  9  objet(s).
Dans la ville  274  le voleur prend  10  objet(s).
Dans la ville  261  le voleur prend  9  objet(s).
Dans la ville  260  le voleur prend  7  objet(s).
Dans la ville  258  le voleur prend  9  objet(s).
Dans la ville  256  le voleur prend  10  objet(s).
Dans la ville  254  le voleur prend  9  objet(s).
Dans la ville  205  le voleur prend  9  objet(s).
Dans la ville  216  le voleur prend  9  objet(s).
Dans la ville  218  le voleur prend  10  objet(s).
Dans la ville  220  le voleur prend  10  objet(s).
Dans la ville  219  le voleur prend  8  objet(s).
Dans la ville  270  le voleur prend  10  objet(s).
Dans la ville  134  le voleur prend  9  objet(s).
Dans la ville  269  le voleur prend  9  objet(s).
Dans la ville  262  le voleur prend  10  objet(s).
Dans la ville  263  le voleur prend  6  objet(s).
Dans la ville  11  le voleur prend  9  objet(s).
Dans la ville  10  le voleur prend  8  objet(s).
Dans la ville  8  le voleur prend  7  objet(s).
Dans la ville  9  le voleur prend  8  objet(s).
Dans la ville  12  le voleur prend  10  objet(s).
Dans la ville  13  le voleur prend  10  objet(s).
Dans la ville  17  le voleur prend  10  objet(s).
Dans la ville  133  le voleur prend  9  objet(s).
Dans la ville  18  le voleur prend  10  objet(s).
Dans la ville  122  le voleur prend  10  objet(s).
Dans la ville  121  le voleur prend  9  objet(s).
Dans la ville  120  le voleur prend  8  objet(s).
Dans la ville  119  le voleur prend  9  objet(s).
Dans la ville  157  le voleur prend  9  objet(s).
Dans la ville  159  le voleur prend  10  objet(s).
Dans la ville  152  le voleur prend  10  objet(s).
Dans la ville  153  le voleur prend  7  objet(s).
Dans la ville  155  le voleur prend  9  objet(s).
Dans la ville  123  le voleur prend  10  objet(s).
Dans la ville  124  le voleur prend  8  objet(s).
Dans la ville  125  le voleur prend  10  objet(s).
Dans la ville  30  le voleur prend  10  objet(s).
Dans la ville  31  le voleur prend  10  objet(s).
Dans la ville  55  le voleur prend  9  objet(s).
Dans la ville  57  le voleur prend  10  objet(s).
Dans la ville  58  le voleur prend  9  objet(s).
Dans la ville  44  le voleur prend  9  objet(s).
Dans la ville  60  le voleur prend  8  objet(s).
Dans la ville  61  le voleur prend  8  objet(s).
Dans la ville  63  le voleur prend  9  objet(s).
Dans la ville  64  le voleur prend  8  objet(s).
Dans la ville  66  le voleur prend  9  objet(s).
Dans la ville  67  le voleur prend  9  objet(s).
Dans la ville  70  le voleur prend  10  objet(s).
Dans la ville  68  le voleur prend  10  objet(s).
Dans la ville  38  le voleur prend  7  objet(s).
Dans la ville  37  le voleur prend  9  objet(s).
Dans la ville  50  le voleur prend  8  objet(s).
Dans la ville  51  le voleur prend  10  objet(s).
Dans la ville  47  le voleur prend  9  objet(s).
Dans la ville  40  le voleur prend  10  objet(s).
Dans la ville  39  le voleur prend  9  objet(s).
Dans la ville  143  le voleur prend  10  objet(s).
Dans la ville  144  le voleur prend  9  objet(s).
Dans la ville  200  le voleur prend  10  objet(s).
Dans la ville  199  le voleur prend  10  objet(s).
Dans la ville  142  le voleur prend  7  objet(s).
Dans la ville  207  le voleur prend  8  objet(s).
Dans la ville  212  le voleur prend  8  objet(s).
Dans la ville  211  le voleur prend  9  objet(s).
Dans la ville  228  le voleur prend  9  objet(s).
Dans la ville  236  le voleur prend  5  objet(s).
Dans la ville  237  le voleur prend  10  objet(s).
Dans la ville  280  le voleur prend  9  objet(s).
Dans la ville  2  le voleur prend  9  objet(s).
Dans la ville  259  le voleur prend  10  objet(s).
Dans la ville  257  le voleur prend  10  objet(s).
Dans la ville  253  le voleur prend  10  objet(s).
Dans la ville  206  le voleur prend  10  objet(s).
Dans la ville  249  le voleur prend  9  objet(s).
Dans la ville  251  le voleur prend  10  objet(s).
Dans la ville  163  le voleur prend  9  objet(s).
Dans la ville  162  le voleur prend  9  objet(s).
Dans la ville  170  le voleur prend  9  objet(s).
Dans la ville  172  le voleur prend  10  objet(s).
Dans la ville  106  le voleur prend  9  objet(s).
Dans la ville  110  le voleur prend  10  objet(s).
Dans la ville  112  le voleur prend  10  objet(s).
Dans la ville  114  le voleur prend  9  objet(s).
Dans la ville  115  le voleur prend  10  objet(s).
Dans la ville  59  le voleur prend  7  objet(s).
Dans la ville  72  le voleur prend  10  objet(s).
Dans la ville  71  le voleur prend  9  objet(s).
Dans la ville  75  le voleur prend  9  objet(s).
Dans la ville  78  le voleur prend  8  objet(s).
Dans la ville  90  le voleur prend  9  objet(s).
Dans la ville  109  le voleur prend  9  objet(s).
Dans la ville  164  le voleur prend  10  objet(s).
Dans la ville  183  le voleur prend  10  objet(s).
Dans la ville  156  le voleur prend  8  objet(s).
Dans la ville  154  le voleur prend  10  objet(s).
Dans la ville  126  le voleur prend  9  objet(s).
Dans la ville  29  le voleur prend  9  objet(s).
Dans la ville  136  le voleur prend  8  objet(s).
Dans la ville  271  le voleur prend  8  objet(s).
Dans la ville  272  le voleur prend  10  objet(s).

In [7]:
eval_non_lin(pi,df_ville,df_object,dict_ville_objet_pris,obj_pris,capacity)

BENEFICE :  1367196
COUT :  16675.702582111688

(1350520.2974178884, 1367196, 16675.702582111688)

In [8]:
eval_lin(pi,df_ville,df_object,dict_ville_objet_pris,obj_pris)

BENEFICE :  1367196
COUT :  4037460124.948373

(-4036092928.948373, 1367196, 4037460124.948373)

In [ ]:
prog_lin(df_ville,df_object,capacity)

Set parameter Username
Set parameter LicenseID to value 2599122
Academic license - for non-commercial use only - expires 2025-12-13
Gurobi Optimizer version 12.0.0 build v12.0.0rc1 (win64 - Windows 10.0 (19045.2))

CPU model: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 81473 rows, 82030 columns and 1176824 nonzeros
Model fingerprint: 0x75f749bf
Model has 78118 quadratic objective terms
Variable types: 840 continuous, 81190 integer (81190 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [1e+00, 1e+03]
  QObjective range [2e+01, 6e+02]
  Bounds range     [1e+00, 3e+02]
  RHS range        [1e+00, 1e+06]
Presolve removed 2794 rows and 285 columns
Presolve time: 2.00s
Presolved: 156518 rows, 159584 columns, 629124 nonzeros
Variable types: 279 continuous, 159305 integer (80910 binary)
Deterministic concurrent LP optimizer: primal simplex, dual simplex, and barrier
Showing barrier log only...

Root barrier log...

Ordering time: 0.13s

Barrier statistics:
 Dense cols : 557
 AA' NZ     : 7.003e+05
 Factor NZ  : 1.634e+06 (roughly 140 MB of memory)
 Factor Ops : 4.707e+08 (less than 1 second per iteration)
 Threads    : 1

                  Objective                Residual
Iter       Primal          Dual         Primal    Dual     Compl     Time
   0  -1.21097075e+14  3.47509805e+13  4.58e+06 4.11e+05  4.80e+09     9s
   1  -9.78585362e+13  5.04132187e+13  3.55e+06 1.24e+04  3.65e+09    10s
   2  -6.06689760e+12  4.79878532e+13  8.23e+04 1.80e+04  1.98e+08    11s
   3  -2.61374269e+12  8.53645541e+12  4.33e+03 8.56e-07  2.93e+07    11s
   4  -5.28078546e+11  1.74882777e+12  5.52e+02 4.97e-07  5.23e+06    12s
   5  -1.94158261e+11  8.20490147e+11  1.78e+02 2.42e-07  2.22e+06    12s
   6  -2.12964643e+10  2.73823034e+11  1.27e+01 1.16e-07  6.25e+05    12s
   7  -1.52265259e+09  2.32975139e+10  4.32e-01 3.81e-08  5.24e+04    13s
   8  -5.77319934e+07  3.96989873e+09  2.50e-12 5.39e-09  8.50e+03    13s
   9  -9.17345604e+06  1.55107618e+08  6.71e-12 5.75e-10  3.47e+02    14s
  10  -1.33997794e+06  8.48493435e+07  1.36e-12 3.40e-10  1.82e+02    14s
  11  -5.94414774e+05  4.88555524e+07  1.42e-12 3.23e-10  1.04e+02    14s
  12  -1.39112294e+05  3.29204026e+07  1.36e-12 4.34e-10  6.97e+01    15s
  13   2.33499558e+04  2.53734819e+07  1.14e-12 4.98e-10  5.35e+01    15s
  14   1.25560115e+05  1.95993634e+07  1.02e-12 3.81e-10  4.11e+01    16s
  15   1.99188106e+05  1.59934996e+07  1.08e-12 4.32e-10  3.33e+01    16s
  16   2.55914574e+05  1.35226057e+07  1.14e-12 4.35e-10  2.80e+01    16s
  17   3.03323885e+05  1.12682147e+07  1.02e-12 4.06e-10  2.31e+01    17s
  18   3.52988911e+05  1.00132452e+07  9.09e-13 4.01e-10  2.04e+01    17s
  19   3.82723882e+05  8.84801893e+06  1.82e-12 3.87e-10  1.79e+01    18s
  20   4.65604637e+05  7.43775564e+06  1.82e-12 3.89e-10  1.47e+01    18s
  21   5.04112330e+05  6.48932725e+06  1.82e-12 4.21e-10  1.26e+01    19s
  22   5.40616996e+05  5.82109199e+06  1.82e-12 3.90e-10  1.11e+01    19s
  23   6.19525921e+05  5.15130192e+06  1.82e-12 4.24e-10  9.56e+00    19s
  24   6.90127419e+05  4.42147629e+06  1.82e-12 3.81e-10  7.87e+00    20s
  25   7.20122466e+05  3.85216680e+06  3.64e-12 4.40e-10  6.61e+00    20s
  26   7.27384412e+05  3.74540840e+06  3.64e-12 4.12e-10  6.37e+00    20s
  27   8.28345757e+05  3.56782193e+06  3.64e-12 3.65e-10  5.78e+00    21s
  28   8.43314499e+05  3.40323529e+06  3.64e-12 4.22e-10  5.40e+00    21s
  29   8.61752450e+05  3.09937182e+06  7.28e-12 4.96e-10  4.72e+00    22s
  30   8.91663203e+05  2.86334807e+06  7.28e-12 3.78e-10  4.16e+00    22s
  31   8.98370357e+05  2.81558521e+06  7.28e-12 4.30e-10  4.04e+00    22s
  32   9.01496949e+05  2.76470993e+06  7.28e-12 4.88e-10  3.93e+00    23s
  33   9.82949990e+05  2.61733145e+06  7.28e-12 5.28e-10  3.45e+00    23s
  34   9.95428978e+05  2.55288958e+06  7.28e-12 4.45e-10  3.29e+00    24s
  35   1.00774093e+06  2.50004987e+06  7.28e-12 6.36e-10  3.15e+00    24s
  36   1.01607457e+06  2.45714334e+06  1.09e-11 8.29e-10  3.04e+00    25s
  37   1.02214565e+06  2.35795335e+06  7.28e-12 6.41e-10  2.82e+00    25s
  38   1.04490987e+06  2.28618024e+06  7.28e-12 5.53e-10  2.62e+00    25s
  39   1.05241292e+06  2.25191777e+06  7.28e-12 6.20e-10  2.53e+00    26s
  40   1.05417307e+06  2.22238176e+06  1.09e-11 8.45e-10  2.46e+00    26s
  41   1.06746688e+06  2.12123369e+06  1.09e-11 4.68e-10  2.22e+00    27s
  42   1.07576205e+06  2.10718276e+06  1.09e-11 5.71e-10  2.18e+00    27s
  43   1.08211976e+06  2.08326533e+06  1.46e-11 5.46e-10  2.11e+00    27s
  44   1.09160796e+06  2.05240302e+06  1.46e-11 6.73e-10  2.03e+00    28s
  45   1.10506396e+06  2.03126495e+06  1.46e-11 6.14e-10  1.95e+00    28s
  46   1.11287418e+06  2.00430125e+06  1.46e-11 7.46e-10  1.88e+00    29s
  47   1.12269560e+06  1.98221590e+06  1.46e-11 9.13e-10  1.81e+00    29s
  48   1.12748634e+06  1.95728829e+06  1.46e-11 7.80e-10  1.75e+00    29s
  49   1.13107691e+06  1.95048173e+06  1.82e-11 9.32e-10  1.73e+00    30s
  50   1.13829438e+06  1.93568854e+06  1.82e-11 9.20e-10  1.68e+00    30s
  51   1.14106435e+06  1.93148816e+06  1.82e-11 8.80e-10  1.67e+00    30s
  52   1.16613928e+06  1.88584401e+06  1.46e-11 7.01e-10  1.52e+00    31s
  53   1.16830393e+06  1.87484855e+06  1.46e-11 3.33e-10  1.49e+00    31s
  54   1.17685645e+06  1.83876683e+06  1.46e-11 3.60e-10  1.40e+00    31s
  55   1.20134685e+06  1.76961756e+06  1.09e-11 3.98e-10  1.20e+00    31s
  56   1.21081306e+06  1.73743328e+06  1.09e-11 5.51e-10  1.11e+00    32s
  57   1.22183622e+06  1.67884709e+06  1.09e-11 5.20e-10  9.64e-01    32s
  58   1.24662826e+06  1.62622011e+06  1.09e-11 6.37e-10  8.01e-01    32s
  59   1.24886829e+06  1.62246392e+06  1.09e-11 9.46e-10  7.88e-01    33s
  60   1.25515326e+06  1.58668685e+06  1.46e-11 4.79e-10  6.99e-01    33s
  61   1.25586407e+06  1.59215265e+06  1.46e-11 6.56e-10  7.09e-01    33s
  62   1.25979215e+06  1.56106565e+06  1.82e-11 3.52e-10  6.36e-01    34s
  63   1.27791283e+06  1.54524766e+06  1.46e-11 3.22e-10  5.64e-01    34s
  64   1.27916798e+06  1.53197505e+06  1.46e-11 3.64e-10  5.33e-01    34s
  65   1.28182957e+06  1.51985569e+06  1.09e-11 4.56e-10  5.02e-01    35s
  66   1.28482398e+06  1.51234316e+06  1.46e-11 4.48e-10  4.80e-01    35s
  67   1.28820317e+06  1.50829787e+06  2.18e-11 5.74e-10  4.64e-01    35s
  68   1.28906778e+06  1.50632118e+06  1.46e-11 5.96e-10  4.58e-01    35s
  69   1.29038859e+06  1.50421283e+06  1.46e-11 5.97e-10  4.51e-01    36s
  70   1.29120972e+06  1.50063301e+06  1.46e-11 6.29e-10  4.42e-01    36s
  71   1.29318522e+06  1.49293324e+06  2.18e-11 4.78e-10  4.21e-01    36s
  72   1.29330237e+06  1.49315900e+06  1.46e-11 5.23e-10  4.22e-01    36s
  73   1.29409350e+06  1.48632758e+06  2.18e-11 5.48e-10  4.06e-01    37s
  74   1.29698554e+06  1.48407555e+06  2.18e-11 4.00e-10  3.95e-01    37s
  75   1.29806610e+06  1.48523724e+06  2.18e-11 5.98e-10  3.95e-01    37s
  76   1.30961698e+06  1.47460899e+06  2.18e-11 6.39e-10  3.48e-01    37s
  77   1.31057325e+06  1.47118252e+06  2.18e-11 3.48e-10  3.39e-01    38s
  78   1.31261136e+06  1.46853765e+06  2.18e-11 3.50e-10  3.29e-01    38s
  79   1.31366890e+06  1.46548753e+06  2.18e-11 3.81e-10  3.20e-01    38s
  80   1.31519319e+06  1.46157667e+06  2.18e-11 6.26e-10  3.09e-01    38s
  81   1.31596276e+06  1.46030484e+06  2.91e-11 7.60e-10  3.05e-01    39s
  82   1.31634137e+06  1.45856203e+06  2.18e-11 8.06e-10  3.00e-01    39s
  83   1.31718240e+06  1.45674211e+06  2.18e-11 7.27e-10  2.94e-01    39s
  84   1.31893167e+06  1.45508342e+06  2.18e-11 7.51e-10  2.87e-01    40s
  85   1.31954170e+06  1.45690274e+06  2.18e-11 6.35e-10  2.90e-01    40s
  86   1.31949732e+06  1.45364134e+06  2.18e-11 5.58e-10  2.83e-01    40s
  87   1.32042370e+06  1.45230960e+06  2.91e-11 3.05e-10  2.78e-01    40s
  88   1.32233020e+06  1.45074409e+06  2.91e-11 3.49e-10  2.71e-01    41s
  89   1.32379826e+06  1.45033246e+06  2.91e-11 4.62e-10  2.67e-01    41s
  90   1.32465904e+06  1.44903254e+06  2.91e-11 4.42e-10  2.62e-01    41s
  91   1.32636828e+06  1.44673579e+06  3.64e-11 4.67e-10  2.54e-01    41s
  92   1.32699696e+06  1.44497469e+06  3.64e-11 4.82e-10  2.49e-01    42s
  93   1.32721018e+06  1.44462312e+06  2.91e-11 5.52e-10  2.48e-01    42s
  94   1.32749452e+06  1.44365816e+06  2.91e-11 6.12e-10  2.45e-01    42s
  95   1.32781208e+06  1.44329117e+06  3.64e-11 3.22e-10  2.44e-01    42s
  96   1.32817797e+06  1.44197747e+06  2.91e-11 3.46e-10  2.40e-01    43s
  97   1.32840422e+06  1.44139838e+06  2.91e-11 3.59e-10  2.38e-01    43s
  98   1.32852292e+06  1.44027417e+06  3.64e-11 3.92e-10  2.36e-01    43s
  99   1.32933589e+06  1.43995215e+06  2.91e-11 3.15e-10  2.33e-01    43s
 100   1.33004508e+06  1.43691178e+06  3.64e-11 3.27e-10  2.25e-01    44s
 101   1.33018557e+06  1.43959745e+06  3.64e-11 4.03e-10  2.31e-01    44s
 102   1.33136242e+06  1.43597689e+06  3.64e-11 3.76e-10  2.21e-01    44s
 103   1.33146823e+06  1.43575206e+06  3.64e-11 3.35e-10  2.20e-01    44s
 104   1.33241299e+06  1.43641427e+06  3.64e-11 4.09e-10  2.19e-01    45s
 105   1.33279614e+06  1.43849796e+06  3.64e-11 3.23e-10  2.23e-01    45s
 106   1.33606909e+06  1.43458438e+06  2.91e-11 3.73e-10  2.08e-01    45s
 107   1.33626944e+06  1.43250709e+06  2.91e-11 2.95e-10  2.03e-01    46s
 108   1.33660609e+06  1.43333448e+06  3.64e-11 3.93e-10  2.04e-01    46s
 109   1.33714024e+06  1.43070494e+06  2.91e-11 4.01e-10  1.97e-01    46s
 110   1.33743422e+06  1.42965701e+06  2.91e-11 2.85e-10  1.95e-01    46s
 111   1.33755097e+06  1.42958258e+06  2.91e-11 4.87e-10  1.94e-01    47s
 112   1.33871915e+06  1.42850887e+06  2.91e-11 4.01e-10  1.89e-01    47s
 113   1.33951794e+06  1.42696346e+06  2.91e-11 3.34e-10  1.84e-01    47s
 114   1.34003924e+06  1.42736706e+06  2.91e-11 5.18e-10  1.84e-01    47s
 115   1.34134021e+06  1.42438202e+06  3.64e-11 7.67e-10  1.75e-01    48s
 116   1.34212204e+06  1.42295326e+06  3.64e-11 4.06e-10  1.71e-01    48s
 117   1.34291653e+06  1.42342808e+06  3.64e-11 3.69e-10  1.70e-01    48s
 118   1.34305561e+06  1.42259928e+06  3.64e-11 4.35e-10  1.68e-01    48s
 119   1.34319527e+06  1.42181943e+06  3.64e-11 3.30e-10  1.66e-01    49s
 120   1.34391121e+06  1.42040447e+06  3.64e-11 4.18e-10  1.61e-01    49s
 121   1.34453011e+06  1.41901975e+06  2.91e-11 4.58e-10  1.57e-01    49s
 122   1.34463642e+06  1.41939320e+06  2.91e-11 7.27e-10  1.58e-01    49s
 123   1.34514861e+06  1.41837217e+06  2.91e-11 6.50e-10  1.54e-01    50s
 124   1.34536371e+06  1.41760765e+06  3.64e-11 2.84e-10  1.52e-01    50s
 125   1.34570301e+06  1.41744160e+06  3.64e-11 3.63e-10  1.51e-01    50s
 126   1.34598994e+06  1.41749553e+06  2.91e-11 4.06e-10  1.51e-01    51s
 127   1.34665273e+06  1.41769009e+06  2.91e-11 3.48e-10  1.50e-01    51s
 128   1.34811405e+06  1.41680734e+06  2.91e-11 2.92e-10  1.45e-01    51s
 129   1.34901043e+06  1.41632669e+06  2.91e-11 3.09e-10  1.42e-01    51s
 130   1.34933858e+06  1.41572877e+06  2.91e-11 3.32e-10  1.40e-01    52s
 131   1.34978493e+06  1.41465260e+06  2.91e-11 4.80e-10  1.37e-01    52s
 132   1.34991679e+06  1.41444775e+06  2.91e-11 5.34e-10  1.36e-01    52s
 133   1.35010901e+06  1.41407432e+06  2.91e-11 4.56e-10  1.35e-01    52s
 134   1.35025168e+06  1.41354506e+06  3.64e-11 3.58e-10  1.34e-01    53s
 135   1.35116622e+06  1.41218478e+06  2.91e-11 4.41e-10  1.29e-01    53s
 136   1.35122877e+06  1.41121050e+06  2.91e-11 7.86e-10  1.27e-01    53s
 137   1.35147629e+06  1.41103723e+06  2.91e-11 8.91e-10  1.26e-01    54s
 138   1.35160202e+06  1.41060643e+06  3.64e-11 9.46e-10  1.24e-01    54s
 139   1.35231853e+06  1.41215623e+06  3.64e-11 2.90e-10  1.26e-01    54s
 140   1.35334275e+06  1.41037524e+06  2.91e-11 3.29e-10  1.20e-01    55s
 141   1.35356304e+06  1.40945657e+06  3.64e-11 3.19e-10  1.18e-01    55s
 142   1.35383124e+06  1.40930850e+06  3.64e-11 7.07e-10  1.17e-01    55s
 143   1.35410291e+06  1.40898816e+06  3.64e-11 6.01e-10  1.16e-01    55s
 144   1.35427781e+06  1.40865354e+06  3.64e-11 3.68e-10  1.15e-01    56s
 145   1.35436427e+06  1.40818937e+06  3.64e-11 4.45e-10  1.14e-01    56s
 146   1.35515727e+06  1.40773038e+06  3.64e-11 3.12e-10  1.11e-01    56s
 147   1.35561557e+06  1.40713672e+06  3.64e-11 4.20e-10  1.09e-01    56s
 148   1.35580822e+06  1.40685969e+06  3.64e-11 4.93e-10  1.08e-01    57s
 149   1.35624713e+06  1.40672528e+06  3.64e-11 4.36e-10  1.06e-01    57s
 150   1.35646225e+06  1.40650692e+06  3.64e-11 3.77e-10  1.06e-01    57s
 151   1.35718521e+06  1.40620766e+06  3.64e-11 3.69e-10  1.03e-01    57s
 152   1.35740993e+06  1.40581767e+06  3.64e-11 3.19e-10  1.02e-01    58s
 153   1.35759973e+06  1.40553336e+06  3.64e-11 5.16e-10  1.01e-01    58s
 154   1.35798152e+06  1.40511584e+06  4.37e-11 6.31e-10  9.94e-02    58s
 155   1.35804618e+06  1.40474017e+06  4.37e-11 3.92e-10  9.85e-02    58s
 156   1.35866907e+06  1.40447039e+06  4.37e-11 2.93e-10  9.66e-02    59s
 157   1.35901376e+06  1.40435153e+06  4.37e-11 4.02e-10  9.56e-02    59s
 158   1.35920856e+06  1.40354542e+06  4.37e-11 5.23e-10  9.35e-02    59s
 159   1.35969882e+06  1.40456820e+06  4.37e-11 5.60e-10  9.47e-02    60s
 160   1.35974706e+06  1.40400572e+06  4.37e-11 7.61e-10  9.34e-02    60s
 161   1.35993948e+06  1.40341173e+06  3.64e-11 3.51e-10  9.17e-02    60s
 162  -1.19971633e+15  3.47509805e+13  4.58e+07 4.11e+05  4.69e+10    61s
 163  -7.40491146e+14  6.65695182e+13  2.73e+07 1.48e-06  2.91e+10    61s
 164  -4.52970361e+12  6.26822266e+13  1.03e+05 1.28e-04  2.52e+08    61s
 165  -2.39537629e+12  4.72724385e+13  2.30e+04 9.74e-05  1.32e+08    61s
 166  -1.72529113e+12  1.65852150e+13  5.13e+03 2.77e-05  4.62e+07    62s
 167  -8.92696499e+11  4.62335179e+12  1.50e+03 7.13e-06  1.30e+07    62s
 168  -2.73161627e+11  1.15840335e+12  3.08e+02 1.57e-06  3.19e+06    62s
 169  -6.06398102e+10  7.65703334e+11  6.19e+01 1.04e-06  1.77e+06    62s
 170  -1.13823742e+10  1.27455012e+11  6.81e+00 1.58e-07  2.93e+05    62s
 171  -1.85526413e+09  1.73791643e+10  8.48e-01 1.72e-08  4.06e+04    63s
 172  -2.27462762e+08  2.47920288e+09  9.71e-02 2.34e-09  5.71e+03    63s
 173  -9.31380306e+06  1.38818389e+08  2.14e-03 5.80e-10  3.13e+02    63s
 174  -2.20788252e+06  8.45389480e+07  5.13e-04 5.20e-10  1.83e+02    63s
 175  -1.12830550e+06  5.19028788e+07  2.95e-04 4.78e-10  1.12e+02    64s
 176  -6.36857699e+05  3.36970120e+07  2.04e-04 4.83e-10  7.24e+01    64s
 177  -3.60465270e+05  2.34806091e+07  1.58e-04 4.22e-10  5.03e+01    64s
 178  -1.87899924e+05  1.67696508e+07  1.31e-04 4.55e-10  3.58e+01    64s
 179  -2.83009705e+04  1.36898809e+07  1.08e-04 3.80e-10  2.89e+01    64s
 180   4.96270092e+05  1.08155424e+07  3.55e-05 3.96e-10  2.18e+01    65s
 181   5.39379707e+05  8.82232901e+06  3.22e-05 3.74e-10  1.75e+01    65s
 182   5.73391809e+05  6.83980249e+06  2.97e-05 3.28e-10  1.32e+01    65s
 183   6.30444925e+05  5.68270855e+06  2.58e-05 3.35e-10  1.07e+01    66s
 184   6.59410151e+05  4.74184382e+06  2.41e-05 4.11e-10  8.61e+00    66s
 185   6.92097095e+05  4.23860040e+06  2.24e-05 4.26e-10  7.48e+00    66s
 186   7.48583293e+05  3.66691170e+06  1.93e-05 4.58e-10  6.16e+00    66s
 187   7.93858537e+05  3.19347159e+06  1.68e-05 4.30e-10  5.06e+00    67s
 188   8.45368149e+05  2.78084843e+06  1.43e-05 4.32e-10  4.08e+00    67s
 189   9.14244488e+05  2.57469818e+06  1.14e-05 3.60e-10  3.50e+00    67s
 190   9.29039675e+05  2.44811738e+06  1.09e-05 4.18e-10  3.20e+00    67s
 191   9.38915579e+05  2.36033823e+06  1.06e-05 4.33e-10  3.00e+00    68s
 192   9.45712210e+05  2.31553649e+06  1.05e-05 4.79e-10  2.89e+00    68s
 193   9.50695739e+05  2.29931653e+06  1.03e-05 4.83e-10  2.85e+00    68s
 194   1.01259278e+06  2.21951408e+06  8.32e-06 5.21e-10  2.55e+00    68s
 195   1.02262570e+06  2.19073729e+06  8.09e-06 6.11e-10  2.46e+00    69s
 196   1.03465196e+06  2.15407402e+06  7.80e-06 5.35e-10  2.36e+00    69s
 197   1.03759239e+06  2.13371493e+06  7.74e-06 5.84e-10  2.31e+00    69s
 198   1.04370940e+06  2.07992495e+06  7.60e-06 5.43e-10  2.19e+00    70s
 199   1.05019656e+06  2.06468361e+06  7.46e-06 5.70e-10  2.14e+00    70s
 200   1.05051323e+06  1.94715913e+06  7.45e-06 5.33e-10  1.89e+00    70s
 201   1.05243904e+06  1.92602681e+06  7.41e-06 5.12e-10  1.84e+00    70s
 202   1.05445746e+06  1.91284822e+06  7.37e-06 5.61e-10  1.81e+00    71s
 203   1.06020881e+06  1.87433356e+06  7.25e-06 5.01e-10  1.72e+00    71s
 204   1.10142226e+06  1.83166480e+06  6.19e-06 4.18e-10  1.54e+00    71s
 205   1.10884039e+06  1.81221759e+06  6.04e-06 5.93e-10  1.48e+00    71s
 206   1.11751505e+06  1.79217141e+06  5.85e-06 6.35e-10  1.42e+00    72s
 207   1.12158010e+06  1.78053191e+06  5.76e-06 7.20e-10  1.39e+00    72s
 208   1.12520546e+06  1.77026426e+06  5.70e-06 6.32e-10  1.36e+00    72s
 209   1.12719751e+06  1.77078542e+06  5.66e-06 5.89e-10  1.36e+00    73s
 210   1.13205463e+06  1.70304597e+06  5.54e-06 3.74e-10  1.20e+00    73s
 211   1.13749776e+06  1.71339661e+06  5.39e-06 3.26e-10  1.21e+00    73s
 212   1.17641778e+06  1.67720427e+06  4.14e-06 3.55e-10  1.06e+00    73s
 213   1.18271450e+06  1.65014952e+06  3.97e-06 3.28e-10  9.86e-01    73s
 214   1.19651413e+06  1.57687147e+06  3.59e-06 3.53e-10  8.02e-01    74s
 215   1.20179626e+06  1.56945187e+06  3.47e-06 5.55e-10  7.76e-01    74s
 216   1.20456343e+06  1.56239712e+06  3.42e-06 4.53e-10  7.55e-01    74s
 217   1.20794017e+06  1.55564523e+06  3.36e-06 4.93e-10  7.34e-01    75s
 218   1.20925813e+06  1.55276261e+06  3.34e-06 4.97e-10  7.25e-01    75s
 219   1.21354895e+06  1.54940961e+06  3.26e-06 6.30e-10  7.09e-01    75s
 220   1.21465475e+06  1.55321694e+06  3.24e-06 5.59e-10  7.14e-01    75s
 221   1.21536679e+06  1.53983440e+06  3.22e-06 4.64e-10  6.85e-01    76s
 222   1.22117501e+06  1.53590498e+06  3.10e-06 3.00e-10  6.64e-01    76s

Barrier performed 222 iterations in 75.96 seconds (28.82 work units)
Barrier solve interrupted - model solved by another algorithm

Concurrent spin time: 47.28s (can be avoided by choosing Method=3)

Solved with dual simplex

Root simplex log...

Iteration    Objective       Primal Inf.    Dual Inf.      Time
   11095    1.3754419e+06   0.000000e+00   0.000000e+00     76s

Root relaxation: objective 1.375442e+06, 11095 iterations, 69.08 seconds (23.21 work units)
Total elapsed time = 76.07s (DegenMoves)
Total elapsed time = 135.37s (DegenMoves)
Total elapsed time = 142.69s (DegenMoves)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 1375441.93    0 4337          - 1375441.93      -     -  153s
H    0     0                    4393.0000000 1375441.93      -     -  156s
H    0     0                    4415.0000000 1375441.93      -     -  156s
H    0     0                    4878.9421371 1375441.93      -     -  166s
H    0     0                    5146.5534802 1375441.93      -     -  170s
H    0     0                    5245.5577538 1375441.93      -     -  170s
H    0     0                    5515.9128467 1375441.93      -     -  172s
H    0     0                    6424.4458615 1375441.93      -     -  176s
H    0     0                    8343.2842228 1375441.93      -     -  176s
H    0     0                    8504.1622953 1375441.93      -     -  176s
H    0     0                    10024.341656 1375441.93      -     -  182s
H    0     0                    10062.955826 1375441.93      -     -  183s
H    0     0                    10094.249444 1375441.93      -     -  193s
H    0     0                    10122.963503 1375441.93      -     -  195s
H    0     0                    10138.699352 1375441.93      -     -  198s
H    0     0                    10141.487231 1375441.93      -     -  199s
H    0     0                    10392.515798 1375427.25      -     -  219s